package com.robloxify.avatar;

import org.jetbrains.annotations.Nullable;

import java.util.ArrayList;
import java.util.EnumMap;
import java.util.List;
import java.util.Map;

import static com.robloxify.avatar.CosmeticCategory.ACCESSORY;
import static com.robloxify.avatar.CosmeticCategory.BODY;
import static com.robloxify.avatar.CosmeticCategory.HAIR;
import static com.robloxify.avatar.CosmeticCategory.ANIMATION;
import static com.robloxify.avatar.CosmeticCategory.EFFECT;
import static com.robloxify.avatar.CosmeticCategory.FACE;
import static com.robloxify.avatar.CosmeticCategory.HAT;
import static com.robloxify.avatar.CosmeticCategory.PANTS;
import static com.robloxify.avatar.CosmeticCategory.SHIRT;

/**
 * The Robloxify avatar catalogue. Everything here is original - the colours, the faces and the
 * geometry are all generated by this mod.
 */
public final class CosmeticCatalog {
	public static final String NONE = "none";

	private static final List<Cosmetic> ALL = new ArrayList<>();
	private static final Map<CosmeticCategory, List<Cosmetic>> BY_CATEGORY = new EnumMap<>(CosmeticCategory.class);
	private static final Map<String, Cosmetic> BY_ID = new java.util.HashMap<>();

	static {
		// Skin tones and hair are free: identity should never be paywalled.
		simple("warm", BODY, "Warm", 0, 0xFFE8B96B);
		simple("light", BODY, "Light", 0, 0xFFF5D6B0);
		simple("tan", BODY, "Tan", 0, 0xFFC68B54);
		simple("deep", BODY, "Deep", 0, 0xFF8D5A32);
		simple("ghost", BODY, "Ghost", 150, 0xFFD8E8F0);

		simple("brown", HAIR, "Brown", 0, 0xFF4A3728);
		simple("black", HAIR, "Black", 0, 0xFF1E1A18);
		simple("blond", HAIR, "Blond", 0, 0xFFE8D07A);
		simple("red", HAIR, "Red", 80, 0xFFB5451F);
		simple("mint", HAIR, "Mint", 120, 0xFF6FD8B8);
		simple("none", HAIR, "Bald", 0, 0x00000000);

		// Faces are all free: expressions should never be paywalled.
		face("neutral", "Neutral", 0xFF3A3A46);
		face("happy", "Happy", 0xFF2B2B36);
		face("surprised", "Surprised", 0xFF33333F);
		face("silly", "Silly", 0xFF3A3A46);
		face("angry", "Angry", 0xFF5A1F1F);
		face("sleepy", "Sleepy", 0xFF3A3A46);

		shirt("classic_blue", "Classic Blue Shirt", 0, 0xFF3B4CCA, 0xFF2A3795, Cosmetic.Pattern.SOLID);
		shirt("red_jacket", "Red Jacket", 150, 0xFFC0392B, 0xFF8E2A20, Cosmetic.Pattern.TRIM);
		shirt("builder_vest", "Builder Vest", 120, 0xFFE67E22, 0xFFFFF3C4, Cosmetic.Pattern.TRIM);
		shirt("ninja_gi", "Ninja Gi", 200, 0xFF23232B, 0xFFB03030, Cosmetic.Pattern.TRIM);
		shirt("rainbow_tee", "Rainbow Tee", 400, 0xFFE74C3C, 0xFFF1C40F, Cosmetic.Pattern.STRIPES);
		shirt("golden_torso", "Golden Torso", 600, 0xFFF1C40F, 0xFFB8860B, Cosmetic.Pattern.SPECKLE);

		pants("classic_green", "Classic Green Pants", 0, 0xFF3FA34D, 0xFF2C7A38, Cosmetic.Pattern.SOLID);
		pants("blue_jeans", "Blue Jeans", 100, 0xFF34495E, 0xFF243447, Cosmetic.Pattern.SOLID);
		pants("black_slacks", "Black Slacks", 120, 0xFF2C2C34, 0xFF1B1B21, Cosmetic.Pattern.SOLID);
		pants("golden_legs", "Golden Legs", 500, 0xFFF1C40F, 0xFFB8860B, Cosmetic.Pattern.SPECKLE);

		hat(NONE, "No Hat", 0, 0, 0, "");
		hat("builder_cap", "Builder Cap", 100, 0xFFFFD23F, 0xFFE0A800, "cap");
		hat("top_hat", "Top Hat", 250, 0xFF1B1B21, 0xFF6E4B2A, "tophat");
		hat("golden_crown", "Golden Crown", 800, 0xFFF1C40F, 0xFFB8860B, "crown");
		hat("headphones", "Headphones", 300, 0xFFE74C3C, 0xFF2C2C34, "headphones");

		accessory(NONE, "No Accessory", 0, 0, 0, "");
		accessory("adventure_backpack", "Adventure Backpack", 200, 0xFF8B5A2B, 0xFF5C3A1A, "backpack");
		accessory("angel_wings", "Angel Wings", 700, 0xFFF5F5F5, 0xFFD8D8E0, "wings");
		accessory("shoulder_pads", "Shoulder Pads", 350, 0xFF7F8C8D, 0xFF56666B, "shoulder_pads");

		effect(NONE, "No Effect", 0, 0, 0, "");
		effect("sparkle_aura", "Sparkle Aura", 250, 0xFF9BE7FF, 0, "sparkle");
		effect("flame_aura", "Flame Aura", 400, 0xFFFF8A3D, 0, "flame");
		effect("golden_aura", "Golden Aura", 600, 0xFFFFD23F, 0, "gold");

		animation("classic", "Classic", 0, "");
		animation("silly", "Silly", 150, "silly");
		animation("ninja", "Ninja", 300, "ninja");
	}

	private CosmeticCatalog() {
	}

	private static void add(Cosmetic cosmetic) {
		ALL.add(cosmetic);
		BY_CATEGORY.computeIfAbsent(cosmetic.category(), key -> new ArrayList<>()).add(cosmetic);
		BY_ID.put(cosmetic.id(), cosmetic);
	}

	private static void simple(String id, CosmeticCategory category, String name, int price, int color) {
		add(new Cosmetic(id, category, name, price, color, 0, Cosmetic.Pattern.SOLID, id));
	}

	private static void face(String id, String name, int ink) {
		add(new Cosmetic(id, FACE, name, 0, ink, 0, Cosmetic.Pattern.SOLID, id));
	}

	private static void shirt(String id, String name, int price, int primary, int secondary, Cosmetic.Pattern pattern) {
		add(new Cosmetic(id, SHIRT, name, price, primary, secondary, pattern, ""));
	}

	private static void pants(String id, String name, int price, int primary, int secondary, Cosmetic.Pattern pattern) {
		add(new Cosmetic(id, PANTS, name, price, primary, secondary, pattern, ""));
	}

	private static void hat(String id, String name, int price, int primary, int secondary, String shape) {
		add(new Cosmetic(id, HAT, name, price, primary, secondary, Cosmetic.Pattern.SOLID, shape));
	}

	private static void accessory(String id, String name, int price, int primary, int secondary, String shape) {
		add(new Cosmetic(id, ACCESSORY, name, price, primary, secondary, Cosmetic.Pattern.SOLID, shape));
	}

	private static void effect(String id, String name, int price, int primary, int secondary, String shape) {
		add(new Cosmetic(id, EFFECT, name, price, primary, secondary, Cosmetic.Pattern.SOLID, shape));
	}

	private static void animation(String id, String name, int price, String shape) {
		add(new Cosmetic(id, ANIMATION, name, price, 0, 0, Cosmetic.Pattern.SOLID, shape));
	}

	public static List<Cosmetic> all() {
		return ALL;
	}

	public static List<Cosmetic> of(CosmeticCategory category) {
		return BY_CATEGORY.getOrDefault(category, List.of());
	}

	@Nullable
	public static Cosmetic byId(String id) {
		return BY_ID.get(id);
	}

	/** The default item of a category, used when nothing is equipped. */
	public static Cosmetic defaultOf(CosmeticCategory category) {
		return of(category).get(0);
	}

	/** Everything a brand new player already owns. */
	public static List<String> startingItems() {
		List<String> ids = new ArrayList<>();
		for (Cosmetic cosmetic : ALL) {
			if (cosmetic.isFree()) {
				ids.add(cosmetic.id());
			}
		}
		return ids;
	}
}
